### PR TITLE
Update AESM errors to version 2.5

### PR DESCRIPTION
**Pull request by jethrogb**

### CODE REVIEW

**Comment by akash-fortanix** [comment]
I was about to ask for the new AESM errors listing but found the link to it in the changed file (in PR). Great!
Here's the [link](https://github.com/intel/linux-sgx/blob/master/psw/ae/inc/internal/aesm_error.h) in case some reviewer wants to take a look.

**Comment by akash-fortanix** [comment]
[Link](https://travis-ci.com/fortanix/rust-sgx/builds/106859391) to build failure log.

**Comment by jethrogb** [comment]
Not due to this PR, filed a bug upstream https://github.com/intel/linux-sgx/issues/389

**Comment by xiangquanliu** [comment]
In command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install protobuf-compiler libsgx-dcap-ql-dev", there is a variable "travis_apt_get_options". So what's the value of it?

**Comment by jethrogb** [comment]
@xiangquanliu I think it's probably `--allow-downgrades --allow-remove-essential --allow-change-held-packages`, see https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/bash/travis_apt_get_options.bash.

**Comment by xiangquanliu** [comment]
From the log, we can see aesmd fail to start. So could you please provide the log of "journalctl -xe" after the installation.
Thanks!

**Comment by jethrogb** [comment]
bors r=akash-fortanix

**Pull request merged**
