### PR TITLE
Fix CI

### LINKED ISSUE #551: Compilation failure of `rustc-serialize` breaks CI
Compilation of `em-app` fails with:

```
em-app$ cargo +nightly-2024-01-05 build --target x86_64-fortanix-unknown-sgx
...
error[E0310]: the parameter type `T` may not live long enough
    --> /home/raoul/.cargo/git/checkouts/rustc-serialize-43e3299849baf4f9/9800ee0/src/serialize.rs:1155:5
     |
1155 |     fn decode<D: Decoder>(d: &mut D) -> Result<Cow<'static, T>, D::Error> {
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |     |
     |     the parameter type `T` must be valid for the static lifetime...
     |     ...so that the type `T` will meet its required lifetime bounds...
     |
note: ...that is required by this bound
    --> /rustc/f688dd684faca5b31b156fac2c6e0ae81fc9bc90/library/alloc/src/borrow.rs:180:30
help: consider adding an explicit lifetime bound
     |
1151 | impl<'a, T: ?Sized + 'static> Decodable for Cow<'a, T>
     |                    +++++++++

For more information about this error, try `rustc --explain E0310`.
error: could not compile `rustc-serialize` (lib) due to 1 previous error
```
Earlier nightlies compiler do not result in this failure. A patch of `rustc-serialize` is required.

### PR DESCRIPTION
**Pull request by raoulstrackx**
Fix #551

### CODE REVIEW

**Review by ssavvides — APPROVED** [review]
LGTM!

**Review by gausk — APPROVED** [review]

**Comment by raoulstrackx** [comment]
bors r=gausk,ssavvides

**Comment by raoulstrackx** [comment]
bors ping

**Comment by raoulstrackx** [comment]
bors ping

**Comment by Taowyoo** [comment]
I guess `bors` public instance maybe already down. Because the words from https://bors.tech/newsletter/2023/06/30/tmib-78/:

> As mentioned [on May 1](https://bors.tech/newsletter/2023/05/01/tmib-76/), bors-ng is deprecated. Bug fixes are still accepted, but new features are not. The public instance will go away once GitHub Merge Queues leave beta.

And  [GitHub merge queue is generally available](https://github.blog/2023-07-12-github-merge-queue-is-generally-available/)

We need to migrate to Github Action now.
I have a in progress PR for this: https://github.com/fortanix/rust-sgx/pull/549

And we could use branch protection settings similar to:
- rust-mbedtls: https://github.com/fortanix/rust-mbedtls/settings/branch_protection_rules/3531452

**Pull request merged**
