### PR TITLE
Replace depricated item 'try!' with '?'

### PR DESCRIPTION
**Pull request by parthsane**
the following files were changed
fortanix-sgx-tools/src/bin/ftxsgx-elf2sgxs.rs
sgxs/src/sgxs.rs
sgxs/src/sigstruct.rs

### CODE REVIEW

**Comment by parthsane** [comment]
closes #186

**Comment by jethrogb** [comment]
CI failed

**Comment by jethrogb** [comment]
Can you please rebase on master?

**Pull request merged**
