### PR TITLE
disable the debugger trap when building for musl

### PR DESCRIPTION
**Pull request by aandyl**
when targeting musl, the rust libc crate does not have a compatible ucontext_t definition. (musl itself will provide one if _GNU_SOURCE is defined, but the libc crate does not do that.)

This change by itself does not result in a working musl build of the enclave runner, due to openssl build issues. When I add the "vendored" openssl feature, I am able to produce a working statically-linked musl build of the enclave runner.

I also tried building with the `rust:alpine` docker image, but that failed with proc macro build problems.

### CODE REVIEW

**Comment by jethrogb** [comment]
This PR did nothing because `target_abi` is never set. I think you mean `target_env`.

**Comment by jethrogb** [comment]
Also, the musl definition of [ucontext_t](https://rust-lang.github.io/libc/x86_64-unknown-linux-musl/libc/struct.ucontext_t.html) seems to be compatible to me.

**Comment by aandyl** [comment]
> Also, the musl definition of [ucontext_t](https://rust-lang.github.io/libc/x86_64-unknown-linux-musl/libc/struct.ucontext_t.html) seems to be compatible to me.

It did not always have gregs. https://github.com/rust-lang/libc/commit/216d8008b661d9a13aa0ccc31f44e35e4ac857b5

Not sure how I came up with `target_abi`. I had originally added a cargo feature and later tried to eliminate it, apparently replacing it with something broken.

**Pull request merged**
