### PR TITLE
Add `#[repr(align)]` to SGX ISA structures

### PR DESCRIPTION
**Pull request by jethrogb**

### CODE REVIEW

**Comment by jethrogb** [comment]
@VardhanThigle did you check this against the documentation?

**Comment by VardhanThigle** [comment]
> @VardhanThigle did you check this against the documentation?

I am extremely sorry for the late reply.
I could verify following data structures from documentation, except for EInitTokenKey (If it is output of EGETKEY, 16 byte alignment might suffice).

| Data structure | Alignemnt | Innstruction |
| ------------------- | ------------- | ---------------- | 
| TCS |	4Kb |  EENTER |
| PageInfo |  32 |  EADD |
| EInitTokenKey |  **4096/16?**  |  EGETKEY |
| SecInfo |  64 |  EMODPE |
| Pcmd |  128 |  eldb:eldu:eldbc:elbuc |
| Sigstruct |  4Kb | EINIT |
| Einittoken |  512 | EINIT |
| Report |  512 | EREPORT |
| TargetInfo |  512 |  EREPORT |
| KeyRequest  | 512 | EGETKEY |

**Comment by jethrogb** [comment]
> EInitTokenKey | 4096/16? | EGETKEY

What are you referring to? There is no datastructure called EInitTokenKey.

**Comment by VardhanThigle** [comment]
> > EInitTokenKey | 4096/16? | EGETKEY
> 
> What are you referring to? There is no datastructure called EInitTokenKey.

Sorry, My bad, got confused with partial opening up of the diff on the GUI. 
That

**Pull request merged**
