### PR TITLE
Bump crate versions ; remove example lock files

### PR DESCRIPTION
**Pull request by ssavvides**
- Bump crate versions of examples
- Removed Cargo.lock and updated .gitignore

### CODE REVIEW

**Comment by Goirad** [comment]
@ssavvides If you fix the conflict and make sure all example locks are removed we can merge this

**Comment by Goirad** [comment]
Please rebase on master

**Comment by Goirad** [comment]
I'm not sure you've rebased, the diff is still huge

**Comment by ssavvides** [comment]
@Goirad

**Comment by Goirad** [comment]
Thanks @ssavvides !
bors r+

**Pull request merged**
